name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh
        env:
          GH_TOKEN: ${{ secrets.AUTH }}

      - name: Increment Version
        id: versioning
        run: |
          LATEST_TAG=$(gh release list --limit 1 | cut -f1)
          if [[ -z "$LATEST_TAG" ]]; then
            # No release found, start with 0.1
            echo "NEW_TAG=v0.1" >> $GITHUB_ENV
          else
            # Split the tag into parts
            VERSION_BITS=(${LATEST_TAG//./ })

            # Increment the minor version
            VNUM1=${VERSION_BITS[0]}
            VNUM2=$((${VERSION_BITS[1]} + 1))

            # Create new tag
            NEW_TAG="$VNUM1.$VNUM2"
            echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          fi

      - name: Set Executable Permission for Gradlew
        run: chmod +x ./gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 -d > my-release-key.keystore

      - name: List all files
        run: ls -lR .

      - name: Build and Sign APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: List all files
        run: ls -lR .

      - name: List APK directory
        run: ls -lR app/build

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_TAG }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH }}

